spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:orderdb;
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    generate-ddl: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
