spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:orderdb;
    username: sa
    password: sa
  jpa:
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  h2:
    console:
      enabled: true
